# Jeff Mentch – personal site
# Restart `bundle exec jekyll serve` after editing this file.

# Site
title: Jeff Mentch
email: jsmentch@mit.edu
description: >-
  Applied scientist building multimodal and perception-driven systems from large-scale real-world data. Harvard–MIT SHBT PhD.

##### for local testing ######  
# baseurl: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsmentch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jshoonm
github_username:  jsmentch
social_link: instagram
social_username: francois_xr

theme_color: black


# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-swiss
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
